// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1726475650);
user_pref("browser.search.region", "ES");
user_pref("calendar.caldav.googleResync", 1726475647);
user_pref("calendar.list.sortOrder", "e0daf03c-7c3d-47fb-acfe-7ec80612f6c4");
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.calendar-main-default", true);
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.calendar-main-in-composite", true);
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.disabled", true);
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.name", "Inici");
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.type", "storage");
user_pref("calendar.registry.e0daf03c-7c3d-47fb-acfe-7ec80612f6c4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Paris");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1726475657136");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1726475647);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230503190012");
user_pref("extensions.lastAppVersion", "102.11.0");
user_pref("extensions.lastPlatformVersion", "102.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"4fca17e9-0920-4f6a-8fb2-9e590c021235\",\"google@search.mozilla.org\":\"c27f5af9-9e27-449b-8d12-412dd77f849e\",\"ddg@search.mozilla.org\":\"0a56bb0a-3564-4cfc-9014-ead822d1e9f0\",\"wikipedia@search.mozilla.org\":\"729b8276-42dc-488f-a357-eca4803f297c\",\"diec2@search.mozilla.org\":\"b08db1c4-39fc-4edc-9692-b660cc1ce0c3\",\"bing@search.mozilla.org\":\"d9329b23-5644-4a55-8037-8d2b59dd9970\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "e3a56dd0-9fbc-4574-8c35-cd1ae498e60");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Feina");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Per fer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Més tard");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.previousBuildID", "20230503190012");
