// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1a52f6c1-cd34-4eaa-9c98-0ed61e6a31ab");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1726176888);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1726176885);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{2cd4ed5a-486a-40e7-b536-0909c39dc147}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1726176878);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{edd8c33f-f6d9-4e89-86ea-c29a1be8fdc6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1726176882);
user_pref("browser.search.region", "ES");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230605223242");
user_pref("browser.startup.homepage_override.mstone", "114.0");
user_pref("browser.startup.lastColdStartupCheck", 1726176880);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1726176883836");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "114.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ES");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9474ac2679cc4a13bc417c1c74e3422c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1726176880);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-ca@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230605223242");
user_pref("extensions.lastAppVersion", "114.0");
user_pref("extensions.lastPlatformVersion", "114.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e450683a-7e15-4564-8a69-61e1ca3b128a\",\"pictureinpicture@mozilla.org\":\"576edd89-6a8f-4220-8278-8dedd42e70a5\",\"screenshots@mozilla.org\":\"2a969e7b-f763-4d1b-8381-d8b3bbeea8c0\",\"webcompat-reporter@mozilla.org\":\"f2d561a2-be49-48b7-ab3c-010a8bb5fc32\",\"webcompat@mozilla.org\":\"153da29c-4603-48bf-8af5-24af8a28ab0b\",\"default-theme@mozilla.org\":\"acbe4963-c296-4185-b03d-f14cbfd0320b\",\"addons-search-detection@mozilla.com\":\"70fde605-5ee9-45fd-a714-fddd72dab0ce\",\"google@search.mozilla.org\":\"b0333299-a5c3-431d-b894-79c0080c182c\",\"wikipedia@search.mozilla.org\":\"819ae7b9-dea0-43d8-850c-841f30371a9a\",\"bing@search.mozilla.org\":\"23f13a32-8ac5-4445-b486-a7485ef73934\",\"ddg@search.mozilla.org\":\"627ec63c-6b2f-462e-9671-aafaf4a1d88e\",\"ebay@search.mozilla.org\":\"aed62781-b18d-4df8-a477-c0c570a04ccd\",\"amazon@search.mozilla.org\":\"4ec63cfe-f3e7-4dcb-a25e-b6cf374c18c9\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"eee47b81-e52c-4f23-bd34-0dafacbd832a\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-09-12T21:34:44.894Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ab45a078-0447-4e8d-877a-6187ab6df9ad");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1726176875);
user_pref("toolkit.telemetry.cachedClientID", "01ba382d-be0f-4f08-8164-b2b86cfdf1dc");
user_pref("toolkit.telemetry.previousBuildID", "20230605223242");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
